export { assertSafeTarget, safeFetch, isPrivateAddress } from './guard.js';
export type { SafeTarget, SafeFetchResult } from './guard.js';
export { VIEWPORT_MATRIX, BASE_DESKTOP, selectViewports } from './devices.js';
export type { ViewportProfile } from './devices.js';
export { ScanBrowser } from './session.js';
export type { PageCapture, ViewportRender, NetworkEntry } from './session.js';
export { runResponsiveProbe } from './probe.js';
export type { ProbeResult, ProbeOffender } from './probe.js';
export { extractSeoDom } from './seoExtract.js';
export type { SeoDomExtract, SeoHeading } from './seoExtract.js';
