import {Activity,ArrowUpRight,Box,Clock3,Code2,FileWarning,Frame,Globe2,LayoutDashboard,MonitorSmartphone,Plus,Search,Settings2,ShieldCheck,Smartphone,Target,TrendingUp,Users,Zap} from '@/components/icons';
const findings=[['High','Mobile bottom sheet interaction','UX & interaction','Validate scroll locking and focus restoration on real devices.'],['High','Production API resilience','Reliability','Gateway failures interrupt data-dependent journeys.'],['Medium','Image delivery consistency','Performance','Large transformations delay meaningful content.']];
const categories=[['Design fidelity',91,'+2.4%'],['User experience',82,'-1.2%'],['Accessibility',96,'+4.1%'],['Performance',74,'-3.8%']];
export default function Home(){return <div className="shell">
 <aside><div className="brand"><span><Target size={19}/></span><b>Northstar</b></div><nav><p>Workspace</p><a className="active"><LayoutDashboard/>Overview</a><a><Box/>Products</a><a><Activity/>Audit runs</a><a><FileWarning/>Findings <em>12</em></a><p>Quality systems</p><a><Frame/>Design fidelity</a><a><MonitorSmartphone/>Device lab</a><a><Code2/>API & backend</a><a><ShieldCheck/>Security</a><p>Manage</p><a><Users/>Team</a><a><Settings2/>Settings</a></nav><div className="usage"><div><Zap size={17}/><b>Quality coverage</b></div><strong>72%</strong><span><i style={{width:'72%'}}/></span><small>9 of 12 systems connected</small></div><div className="profile"><span>AO</span><div><b>Alex Owner</b><small>Product lead</small></div></div></aside>
 <main><header><div><h1>Good morning, Alex.</h1><p>Here is the quality posture across your products.</p></div><div className="actions"><button className="search"><Search/>Search</button><button className="primary"><Plus/>New product</button></div></header>
 <section className="alert"><span><Activity/></span><div><b>3 release blockers need attention</b><p>Two reliability findings and one mobile interaction issue are open.</p></div><button>Review blockers <ArrowUpRight/></button></section>
 <section className="metrics"><article><div><span>Portfolio score</span><TrendingUp/></div><strong>86<small>/100</small></strong><p className="up">↑ 4.2% <i>from last month</i></p></article><article><div><span>Products monitored</span><Globe2/></div><strong>6</strong><p>4 web · 2 mobile</p></article><article><div><span>Open findings</span><FileWarning/></div><strong>12</strong><p className="danger">3 release blockers</p></article><article><div><span>Last audit</span><Clock3/></div><strong className="time">8m ago</strong><p>Wisdom Church · Production</p></article></section>
 <div className="grid"><section className="panel portfolio"><div className="panelHead"><div><h2>Product portfolio</h2><p>Quality status across active products</p></div><button>View all <ArrowUpRight/></button></div><div className="product"><div className="appIcon gold"><Globe2/></div><div className="productName"><b>Wisdom Church</b><span>Web · Production</span></div><div className="score"><i>78</i><span>Needs attention</span></div><div className="productMeta"><b>3</b><span>Open findings</span></div><div className="devices"><MonitorSmartphone/><Globe2/></div><button className="run">Run audit</button></div><div className="product"><div className="appIcon purple"><Smartphone/></div><div className="productName"><b>Commerce Mobile</b><span>iOS & Android · Staging</span></div><div className="score good"><i>94</i><span>Release ready</span></div><div className="productMeta"><b>2</b><span>Open findings</span></div><div className="devices"><Smartphone/></div><button className="run">Run audit</button></div><div className="product"><div className="appIcon blue"><Code2/></div><div className="productName"><b>Payments API</b><span>API · Production</span></div><div className="score good"><i>91</i><span>Healthy</span></div><div className="productMeta"><b>1</b><span>Open finding</span></div><div className="devices"><Code2/></div><button className="run">Run audit</button></div></section>
 <section className="panel quality"><div className="panelHead"><div><h2>Quality signals</h2><p>Portfolio-wide categories</p></div></div>{categories.map(([n,s,d])=><div className="signal" key={n}><div><span>{n}</span><b className={String(d).startsWith('-')?'down':'up'}>{d}</b></div><div className="bar"><i style={{width:`${s}%`}}/></div><strong>{s}</strong></div>)}</section></div>
 <section className="panel findings"><div className="panelHead"><div><h2>Priority findings</h2><p>Issues with the highest impact on your users and releases</p></div><button>View all findings <ArrowUpRight/></button></div><div className="table"><div className="tr labels"><span>Severity</span><span>Finding</span><span>System</span><span>Status</span></div>{findings.map((f,i)=><div className="tr" key={f[1]}><span><i className={i<2?'high':'medium'}>{f[0]}</i></span><span><b>{f[1]}</b><small>{f[3]}</small></span><span>{f[2]}</span><span><i className="open">Open</i></span></div>)}</div></section>
 </main></div>}
