import Fastify from 'fastify';
import cors from '@fastify/cors';
import { createProjectSchema, runOptionsSchema } from '@quality/contracts';
import { store } from './store.js';
import { auditProject, assertSafeTarget } from './auditor.js';
const app = Fastify({logger:true,requestTimeout:30_000,bodyLimit:64_000});
await app.register(cors,{origin:process.env.CORS_ORIGIN?.split(',')??true});
app.get('/health',async()=>({status:'ok',service:'quality-api',time:new Date().toISOString()}));
app.get('/v1/projects',async()=>({data:store.listProjects()}));
app.post('/v1/projects',async(req,reply)=>{const parsed=createProjectSchema.safeParse(req.body);if(!parsed.success)return reply.code(400).send({error:'VALIDATION_ERROR',details:parsed.error.flatten()});if(parsed.data.targetUrl)try{await assertSafeTarget(parsed.data.targetUrl)}catch(error){return reply.code(400).send({error:'UNSAFE_TARGET',message:(error as Error).message})}return reply.code(201).send({data:store.createProject(parsed.data)});});
app.get('/v1/runs',async req=>({data:store.listRuns((req.query as {projectId?:string}).projectId)}));
app.get('/v1/runs/:id',async(req,reply)=>{const run=store.getRun((req.params as {id:string}).id);return run?{data:run}:reply.code(404).send({error:'RUN_NOT_FOUND'});});
app.post('/v1/projects/:id/runs',async(req,reply)=>{const projectId=(req.params as {id:string}).id;const project=store.getProject(projectId);if(!project)return reply.code(404).send({error:'PROJECT_NOT_FOUND'});const options=runOptionsSchema.safeParse(req.body??{});if(!options.success)return reply.code(400).send({error:'VALIDATION_ERROR',details:options.error.flatten()});const run=store.createRun(projectId);setImmediate(async()=>{store.updateRun(run.id,{status:'running'});try{const result=await auditProject(project);store.updateRun(run.id,{...result,status:result.findings.some(f=>['critical','high'].includes(f.severity))?'failed':'passed',completedAt:new Date().toISOString()})}catch(error){app.log.error(error);store.updateRun(run.id,{status:'failed',score:0,error:(error as Error).message,completedAt:new Date().toISOString()})}});return reply.code(202).send({data:run});});
app.setErrorHandler((error,_req,reply)=>{app.log.error(error);reply.code(500).send({error:'INTERNAL_ERROR'});});
await app.listen({port:Number(process.env.API_PORT||4100),host:'0.0.0.0'});
